fail_fast: true

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      #- id: no-commit-to-branch  # prevent direct commits to main branch
      #args: [--branch, main]
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-sort-keys
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [ --maxkb=1000 ]
      - id: detect-private-key
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: check-merge-conflict
      - id: check-docstring-first
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.22.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
